"""
Visualize CNN channel activation statistics for a trained GaWF model.

Reads cnn_channel_activation_stats.npz (generated by analysis_cnn_channel_activation.py)
and produces a 32x10 heatmap figure with:
    - Left:  raw mean activations (channels x digits).
    - Right: row-wise z-score across digits for each channel.

Output:
    cnn_channel_activation_matrix.png in --output_dir.
"""

import argparse
import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402


def parse_args() -> argparse.Namespace:
    """Parse command line arguments for visualization."""
    parser = argparse.ArgumentParser(
        description="Plot CNN channel activation matrix (mean and z-score variants)."
    )
    parser.add_argument(
        "--input_path",
        type=str,
        default="./results/cnn_channel_activation_data",
        help=(
            "Path to cnn_channel_activation_stats.npz. If a directory is given, "
            "file name will be auto-completed as 'cnn_channel_activation_stats.npz'."
        ),
    )
    parser.add_argument(
        "--save_dir",
        type=str,
        default="./results/cnn_channel_activation_figs",
        help="Directory to save figures.",
    )
    parser.add_argument(
        "--channel_order_path",
        type=str,
        default="./results/cnn_channel_activation_data/channel_order_by_cosine_similarity.npy",
        help=(
            "Path to a NumPy array specifying the feature-channel order to use "
            "for visualization (e.g., output from analyze_cnn_channel_activation.py). "
            "If missing or invalid, the natural order [0..C-1] is used."
        ),
    )
    parser.add_argument(
        "--z_mode",
        type=str,
        default="row-wise",
        choices=["row-wise", "col-wise", "global"],
        help=(
            "Z-score normalization mode for the right heatmap: "
            "'row-wise' (per channel across digits), "
            "'col-wise' (per digit across channels), "
            "'global' (entire matrix). Default: row-wise."
        ),
    )
    return parser.parse_args()


def load_stats(stats_path: str):
    """
    Load activation statistics from npz file.

    Returns
    -------
    mean_activation : np.ndarray
        Array of shape (32, 10).
    std_activation : np.ndarray
        Array of shape (32, 10).
    digit_sample_count : np.ndarray
        Array of shape (10,).
    """
    obj = np.load(stats_path)
    mean_activation = np.asarray(obj["mean_activation"], dtype=np.float32)
    std_activation = np.asarray(obj["std_activation"], dtype=np.float32)
    digit_sample_count = np.asarray(obj["digit_sample_count"])

    if mean_activation.shape != (32, 10):
        raise ValueError(
            f"Expected mean_activation shape (32, 10), got {mean_activation.shape}"
        )
    if std_activation.shape != (32, 10):
        raise ValueError(
            f"Expected std_activation shape (32, 10), got {std_activation.shape}"
        )
    if digit_sample_count.shape != (10,):
        raise ValueError(
            f"Expected digit_sample_count shape (10,), got {digit_sample_count.shape}"
        )
    return mean_activation, std_activation, digit_sample_count


def load_channel_order(path: str, num_channels: int) -> np.ndarray:
    """
    Load channel order from a .npy file if available; otherwise fall back to [0..C-1].
    """
    default_order = np.arange(num_channels, dtype=np.int64)

    if path is None or path == "":
        return default_order

    abs_path = os.path.abspath(path)
    if not os.path.isfile(abs_path):
        print(
            f"[viz][warn] channel order file not found at '{abs_path}'; "
            "using default channel order."
        )
        return default_order

    try:
        order = np.load(abs_path)
    except Exception as exc:  # noqa: BLE001
        print(
            f"[viz][warn] failed to load channel order from '{abs_path}' "
            f"({exc}); using default channel order."
        )
        return default_order

    order = np.asarray(order, dtype=np.int64)
    if order.ndim != 1 or order.size != num_channels:
        print(
            "[viz][warn] channel order has incompatible shape "
            f"{order.shape} for num_channels={num_channels}; "
            "using default channel order."
        )
        return default_order

    # Flip so that earlier entries in 'order' are mapped to
    # visually higher rows (larger row indices with origin='lower').
    return order[::-1]


def compute_zscore(mean_activation: np.ndarray, mode: str) -> np.ndarray:
    """
    Compute z-score for the activation matrix under different normalization modes.
    
    Modes
    -----
    - 'row-wise':  per-channel across digits (default, original behavior).
    - 'col-wise':  per-digit across channels.
    - 'global':    over the whole 32x10 matrix.
    """
    C, D = mean_activation.shape
    if C != 32 or D != 10:
        raise ValueError(
            f"Expected mean_activation of shape (32, 10), got {mean_activation.shape}"
        )

    if mode == "row-wise":
        z = np.zeros_like(mean_activation, dtype=np.float32)
        for c in range(C):
            row = mean_activation[c]
            mu = float(row.mean())
            sigma = float(row.std())
            if sigma < 1e-8:
                sigma = 1e-8
            z[c] = (row - mu) / sigma
        return z

    if mode == "col-wise":
        z = np.zeros_like(mean_activation, dtype=np.float32)
        for d in range(D):
            col = mean_activation[:, d]
            mu = float(col.mean())
            sigma = float(col.std())
            if sigma < 1e-8:
                sigma = 1e-8
            z[:, d] = (col - mu) / sigma
        return z

    if mode == "global":
        mu = float(mean_activation.mean())
        sigma = float(mean_activation.std())
        if sigma < 1e-8:
            sigma = 1e-8
        return (mean_activation - mu) / sigma

    raise ValueError(f"Unknown z-score mode: {mode}")


def plot_activation_matrices(
    mean_activation: np.ndarray,
    z_scores: np.ndarray,
    digit_sample_count: np.ndarray,
    out_path: str,
    z_mode: str,
) -> None:
    """
    Plot mean activation and row-wise z-score matrices side by side and save as PNG.
    """
    C, D = mean_activation.shape
    if z_scores.shape != (C, D):
        raise ValueError(
            f"z_scores shape {z_scores.shape} does not match mean_activation shape {mean_activation.shape}"
        )

    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    # Match height with UxV 32x256 matrices in viz_gawf_sector_basis (figsize=(8, 5))
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # Left: raw mean activation
    ax0 = axes[0]
    im0 = ax0.imshow(
        mean_activation,
        origin="lower",
        interpolation="nearest",
        aspect="auto",
    )
    ax0.set_title("Raw Mean Activation\n(CNN Channels × Digits)")
    ax0.set_xlabel("Digit label (0–9)")
    ax0.set_ylabel("Channel index (0–31)")
    ax0.set_xticks(range(D))
    ax0.set_xticklabels([str(d) for d in range(D)])
    # Channel ticks: start at 0, step 5 (0,5,...,30)
    yticks = list(range(0, C, 5))
    ax0.set_yticks(yticks)
    ax0.set_yticklabels([str(c) for c in yticks])
    fig.colorbar(im0, ax=ax0)

    # Right: z-score heatmap
    ax1 = axes[1]
    im1 = ax1.imshow(
        z_scores,
        origin="lower",
        interpolation="nearest",
        aspect="auto",
        vmin=-3,
        vmax=3,
        cmap="RdBu_r",
    )
    if z_mode == "row-wise":
        title = "Row-wise Z-score Across Digits"
    elif z_mode == "col-wise":
        title = "Column-wise Z-score Across Channels"
    else:
        title = "Global Z-score (All Entries)"
    ax1.set_title(f"{title}\n(CNN Channels × Digits)")
    ax1.set_xlabel("Digit label (0–9)")
    ax1.set_ylabel("Channel index (0–31)")
    ax1.set_xticks(range(D))
    ax1.set_xticklabels([str(d) for d in range(D)])
    ax1.set_yticks(yticks)
    ax1.set_yticklabels([str(c) for c in yticks])
    fig.colorbar(im1, ax=ax1)

    fig.suptitle(
        "CNN Channel Activation Statistics\n"
        + "Per-digit sample counts: "
        + ", ".join(f"{d}:{int(n)}" for d, n in enumerate(digit_sample_count)),
        fontsize=10,
    )
    fig.tight_layout(rect=[0, 0.03, 1, 0.95])
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"Saved activation matrix figure to: {out_path}")


def main() -> None:
    args = parse_args()

    raw_in_path = args.input_path
    if raw_in_path is None or raw_in_path == "":
        raw_in_path = "./cnn_channel_activation_data"
    # If input_path is a directory or lacks an extension, auto-complete filename.
    if os.path.isdir(raw_in_path) or not os.path.splitext(raw_in_path)[1]:
        raw_in_path = os.path.join(raw_in_path, "cnn_channel_activation_stats.npz")

    stats_file = os.path.abspath(raw_in_path)

    save_dir = os.path.abspath(args.save_dir)
    os.makedirs(save_dir, exist_ok=True)
    suffix = {
        "row-wise": "rowwise",
        "col-wise": "colwise",
        "global": "global",
    }[args.z_mode]
    out_path = os.path.join(save_dir, f"cnn_channel_activation_matrix_{suffix}.png")

    mean_activation, std_activation, digit_sample_count = load_stats(stats_file)

    # Reorder feature channels according to cosine-based order (if provided).
    C, _ = mean_activation.shape
    channel_order = load_channel_order(args.channel_order_path, num_channels=C)
    mean_activation = mean_activation[channel_order]

    z_scores = compute_zscore(mean_activation, mode=args.z_mode)

    plot_activation_matrices(
        mean_activation=mean_activation,
        z_scores=z_scores,
        digit_sample_count=digit_sample_count,
        out_path=out_path,
        z_mode=args.z_mode,
    )


if __name__ == "__main__":
    main()

